CREATE TABLE profile (
profileId INT UNSIGNED AUTO_INCREMENT NOT NULL,
profileDateCreated TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL,
profileEmail VARCHAR (128) NOT NULL,
profileUserDob DATE,
UNIQUE (profileEmail),
UNIQUE (profileId)
);
CREATE TABLE post (
postId INT UNSIGNED NOT NULL,
postProfileId INT UNSIGNED NOT NULL,
postContent VARCHAR(255),
postDateTime TIMESTAMP DEFAULT CURRENT_TIMESTAMP NOT NULL
);
CREATE TABLE